WebApplicationskillmine/Models/Book.cs
namespace WebApplicationskillmine.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
    }
}

WebApplicationskillmine/Models/Employee.cs
namespace WebApplicationskillmine.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Salary  { get; set; }
        public string Phoneno { get; set; }
    }
}

WebApplicationskillmine/Models/ErrorViewModel.cs
namespace WebApplicationskillmine.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplicationskillmine/Models/Product.cs
namespace WebApplicationskillmine.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
    }
}

WebApplicationskillmine/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationskillmine.Models;

namespace WebApplicationskillmine.Controllers
{
    public class BookController : Controller
    {
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Book book)
        {
            ViewBag.Id = book.Id;
            ViewBag.Name=book.Name;
            ViewBag.Price=book.Price;
            return View("Show");
        }
    }
}

WebApplicationskillmine/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationskillmine.Models;

namespace WebApplicationskillmine.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Employee emp)
        {
            ViewBag.Id = emp.Id;
            ViewBag.Name = emp.Name;
            ViewBag.Price = emp.Salary;
            ViewBag.Phoneno = emp.Phoneno;
            return View("Show");
        }
    }
}

WebApplicationskillmine/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplicationskillmine.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApplicationskillmine/Controllers/PersonController.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Runtime.InteropServices;

namespace WebApplicationskillmine.Controllers
{
    public class PersonController : Controller
    {
        [HttpGet]
        public IActionResult PersonDetails()
        {
            List<string> cities = new List<string>() { "select city","pune", "Nashik", "Latur", "Nagar", "Solapur" };
            ViewData["cities"] = newSelectList(cities);
            return View();
        }

        private object newSelectList(List<string> cities)
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        public IActionResult PersonDetails(IFormCollection form,ICollection<string> hobbies)
        {
            ViewBag.Name = form["Name"];
            ViewBag.Phone = form["phone"];
            ViewBag.Gender = form["Gender"];
            ViewBag.city = form["cities"];
            ViewBag.Hobbies=hobbies;
            return View("Details");
        }
    }
}

WebApplicationskillmine/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationskillmine.Models;
namespace WebApplicationskillmine.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ProductList()
        {
            List<Product> products = new List<Product>()
            {
                new Product {Id=1,Name="laptop",Price=30000 },
                new Product {Id = 2, Name = "mobile", Price = 20000 },
               new Product { Id = 3, Name = "watch", Price = 3000 },
            };
            ViewData["productlist"]=products;
            //return View();

            TempData["message"] = "welcome to the mvc core";
            TempData.Keep("message");
            
                List<Product> products1 = new List<Product>()
                {
                new Product {Id=1,Name="laptop",Price=30000 },
                new Product {Id = 2, Name = "mobile", Price = 20000 },
               new Product { Id = 3, Name = "watch", Price = 3000 },
                };
                ViewBag.productlist = products1;
                return View();
            
            
        }
       
    }
}

WebApplicationskillmine/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace WebApplicationskillmine.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Registrationform()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Registrationform(IFormCollection form)
        {
            ViewBag.Name = form["Name"];
            ViewBag.Gender = form["Gender"];
            ViewBag.Mobileno = form["Mobileno"];
            ViewBag.Email = form["email"];
            ViewBag.Percentage = form["percentage"];
            return View("Display");
        }
    }
}

WebApplicationskillmine/Views/Book/Create.cshtml
@model WebApplicationskillmine.Models.Book

@{
    ViewData["Title"] = "Create";
}



<h4>Book</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplicationskillmine/Views/Book/Show.cshtml
@{
    ViewData["Title"] = "Show";
}



<h1>Book detail</h1>
<p>
    <b>Id</b>:@ViewBag.Id
</p>
<p>
    <b> Name</b>@ViewBag.Name
</p>
<p>
    <b> Price</b>@ViewBag.Price
</p>

WebApplicationskillmine/Views/Employee/Create.cshtml
@model WebApplicationskillmine.Models.Employee

@{
    ViewData["Title"] = "Create";
}



<h4>Employee</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phoneno" class="control-label"></label>
                <input asp-for="Phoneno" class="form-control" />
                <span asp-validation-for="Phoneno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplicationskillmine/Views/Employee/Show.cshtml
@{
    ViewData["Title"] = "Show";
}

<h1>Show</h1>

 <table class="table table-bordered">
        <tr>
            <th>Emp Id</th>
            <td>@ViewBag.Id</td>
        </tr>
        <tr>
            <th>Emp Name</th>
            <td>@ViewBag.Name</td>
        </tr>
         <tr>
            <th>Emp Salary</th>
            <td>@ViewBag.Salary</td>
        </tr>
        <tr>
            <th>Emp Phoneno</th>
        <td>@ViewBag.Phoneno</td>
        </tr>
        </table>

WebApplicationskillmine/Views/Home/Aboutus.cshtml
@{
    ViewData["Title"] = "Aboutus";
}

<h1>Aboutus</h1>
<div class="container">
    <div class="row">
        <div class="col-4">1</div>
         <div class="col-4">2</div>
        <div class="col-4">3</div>

    </div>
</div>

WebApplicationskillmine/Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = "ContactUs";
}

<h1>ContactUs</h1>

WebApplicationskillmine/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <h2>
        @TempData["message"]
    </h2>
    @if(ViewData["Colors"]!=null)
    {
    <div class="row">
        <div col-12>
            <ol>
                @foreach (string color in (IEnumerable<string>)ViewData["Colors"])
                {
                    <li>
                        @color
                    </li>
                }
            </ol>
        </div>
    </div>
    }
</div>

WebApplicationskillmine/Views/Person/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

    <table class="table table-bordered">
        <tr>
            <th>Person Name</th>
            <td>@ViewBag.Name</td>
        </tr>
        <tr>
            <th>Person Phone</th>
            <td>@ViewBag.Phone</td>
        </tr>
         <tr>
            <th>Person Gender</th>
            <td>@ViewBag.Gender</td>
        </tr>
        <tr>
            <th>city</th>
        <td>@ViewBag.city</td>
        </tr>
        <tr>
            <th>Hobbies</th>
            <td>
                @foreach(string s in ViewBag.Hobbies)
                {
                    <p>
                        @s
                    </p>
                }
            </td>
        </tr>
    </table>

WebApplicationskillmine/Views/Person/PersonDetails.cshtml
@{
    ViewData["Title"] = "PersonDetails";
}


@using(Html.BeginForm())
{
    <h3>PersonDetails</h3>
<div class="mb-3">
    <label>Enter name</label>
    @Html.TextBox("Name")
</div>
<div class="mb-3">
    <label>phone</label>
    @Html.TextBox("phone")
</div>
<div class="mb-3">
    <label>Enter Gender</label>
    <input type="radio" name="Gender" value="Male" />Male
    <input type="radio" name="Gender" value="Female" />Female
</div>
<div class="mb-3">
    <label> enter hobbies</label>
    <input type="checkbox" name="hobbies" value="Reading" />Reading
    <input type="checkbox" name="hobbies" value="Sport" />Sport
    <input type="checkbox" name="hobbies" value="travel" />Travel
</div>
<div class="mb-3">
    <label>select city</label>
    @Html.DropDownList("cities")
</div>
<div class="mb-3">
    
    <input type="submit" valve="Save Form" />
</div>
}

WebApplicationskillmine/Views/Product/ProductList.cshtml
@{
    ViewData["Title"] = "ProductList";
}

<h1>ProductList</h1>
<h2>
    @TempData["message"];
</h2>
@if(ViewData["productlist"]!=null)
{
    <table class="container table-bordered">
       <tr>
           <th>Id</th>
           <th>Name</th>
           <th>Price</th>
       </tr>
    @foreach (Product p in (IEnumerable<Product>)ViewData["productlist"])
    {
        <tr>
            <td>@p.Id</td>
            <td>@p.Name</td>
            <td>@p.Price</td>
        </tr>
    }

    </table>
}
<h3>Productlist using viewbag</h3>
<table class="container table-bordered">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Price</th>
    </tr>
    @foreach (Product p in ViewBag.productlist)
    {
        <tr>
            <td>@p.Id</td>
            <td>@p.Name</td>
            <td>@p.Price</td>
        </tr>
    }

</table>

WebApplicationskillmine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationskillmine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationskillmine.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationskillmine</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Aboutus">About Us</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ProductList">ProductList</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="PersonDetails">Survey Form</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Create">Add Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Create">Employee Detail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Registrationform">Studentform</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplicationskillmine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplicationskillmine/Views/Student/Display.cshtml
@{
    ViewData["Title"] = "Display";
}

<h1>Display</h1>
<p>
    Name:@ViewBag.Name
</p>
<p>
    Gender:@ViewBag.Gender
</p>
<p>
    Mobileno:@ViewBag.Mobileno
</p>
<p>
    Email:@ViewBag.Email
</p>
<p>
    Percentage:@ViewBag.Percentage
</p>

WebApplicationskillmine/Views/Student/Registrationform.cshtml
 
@{
    ViewData["Title"] = "Registrationform";
}

<h1>Registrationform</h1>

@using(Html.BeginForm())
{
    <table>
        <tr>
            <th>Enter name</th>
            <td>@Html.TextBox("Name")</td>
        </tr>
        <tr>
            <th>Gender</th>
            <td>@Html.RadioButton("Gender","Male")Male
            @Html.RadioButton("Gender","FeMale")Female
            </td>
        </tr>
            <tr>
            <th>Enter Mobileno</th>
                <td>@Html.TextBox("Mobileno")</td>
            </tr>
                <tr>
            <th>Enter email</th>
                <td>@Html.TextBox("email")</td>
            </tr>
        <tr>
            <th>Enter Percentage</th>
            <td>@Html.TextBox("percentage")</td>
        </tr>
            
    </table>
    <input type="submit" value="save"/>
    <a href="Index">home</a>
}